### ISSUE TITLE
Bug: Revoke access does not work

### ISSUE THREAD

**Issue by woutslabbinck** [SolidLabResearch/loama#1]
When revoking access using the interface, a PATCH request is sent to the given authorization source.

The HTTP PATCH request uses `application/sparql-update` to update the authorization resource.
The payload consists then of both a `DELETE DATA {...}` sparql update (which is desired) and an `INSERT DATA {...}` sparql update.
Since the latter in my tests contain similar data, the permission remains (the only difference noted is a different URI fragment id).

I do not know where in the code these wrong addition of permission (the content of the `INSERT DATA`) is generated, but that appears to be the problem.

**Comment by NuttyShrimp** [comment]
Hey, can U check if you still have any related problems with granting/revoking permissions on the following repo & branch https://github.com/NuttyShrimp/loama/tree/fix/missing-acl-updates ?

**Comment by woutslabbinck** [comment]
Hey, I just ran the branch `fix/missing-acl-updates` and tested out the application.

I still have similar problems if I connect with a new Solid pod (I use one at solidweb.me).

It has no index.json file and the `.acl` is private.

When I execute turn on `able to read data` and turn off `able to read data` once, everything seems to be fine (that is both the .acl and the index.json)
But once I do it multiple times, logging in and out of loama again. I tend to get new IDs PATCH (insert) in the `.acl` resource which is not present in the `index.json` file. 

It seems that there is something out of sync (the index.json is out of sync with the actual `.acl` for some reason).

**Comment by NuttyShrimp** [comment]
The controller rewrite has introduced a couple of locks to prevent the index from going out of sync & should fix itself when it happens. Could you check if you still have this issue? I wasn't able to reproduce the issue anymore

**Comment by woutslabbinck** [comment]
It seems to work perfectly!
I have not been able to reproduce it myself.
