### ISSUE TITLE
Containers in Containers are not displayed

### ISSUE THREAD

**Issue by elsdvlee** [SolidLabResearch/loama#34]
E.g. 
Login with oidc provider https://css1.onto-deside.ilabt.imec.be/, webid https://css1.onto-deside.ilabt.imec.be/lindner-group/profile/card#me, email info@lindner-group.com, password lindner123

The container 'data' contains also a container named 'dt' in which is not displayed. 
And it is needed to go even one more container deeper ('out') to come to the actual RDF files: 
- data/dt/out/boms.ttl
- data/dt/out/materials.ttl
- data/dt/out/products.ttl

**Comment by NuttyShrimp** [comment]
This should be fixed with d803d32008c2dcb99a500195bbdbd83d4af203c7
