### ISSUE TITLE
Dangerous operations can happen as an accident

### ISSUE THREAD

**Issue by woutslabbinck** [SolidLabResearch/loama#4]
As of today, the dangerous operation of giving `acl:Control` permission (`Able to manage access & permissions` in the UI) is done by just clicking the checkbox.

The desired outcome should be that a warning is given when trying to give this permission to another user. If a user then deliberately states that this was desired, control access should then be given.

**Comment by NuttyShrimp** [comment]
Would something like this be sufficient when ticking the checkbox for the control permission?

![image](https://github.com/user-attachments/assets/2243ab8a-ec88-4503-9903-a96765223f9f)

**Comment by woutslabbinck** [comment]
Yes, that makes sense to me
