### ISSUE TITLE
Cold start with index resource (optimisation)

### ISSUE THREAD

**Issue by woutslabbinck** [SolidLabResearch/loama#7]
When using LOAMA with an existing pod, the index resource will be empty.

When using the application through granting or revoking access, this index resource is updated.

However, when traversing the resources in a pod using LOAMA (by pressing `view files`), the authorization resources within a container are requested nonetheless without updating the index file.

Desired outcome: update the index resource more frequently.

**Comment by NuttyShrimp** [comment]
I would suggest loading all the permission info of the (container) resources of the current container resource, see below for an example.
This is a better approach for people with a lot of files in their pod as the controller currently sends out at least 6 requests per file to get all the necessary info. 

e.g.
- You log in to your pod -> all the permissions for the (container) resources at the "home" of your pod are loaded into the index (README, the profile container, ...)
- You enter the "profile" directory - all the permissions for the (container) resources linked to this container resource are loaded.

**Comment by woutslabbinck** [comment]
>  the controller currently sends out at least 6 requests per file to get all the necessary info.

6 requests? That is a lot for one resource. Could you maybe elaborate why 6 are sent (which ones and for what purpose)?

To comment on the approach for loading the index, it makes sense to only load them in on container level. That is only when selected.

**Comment by NuttyShrimp** [comment]
> 6 requests? That is a lot for one resource. Could you maybe elaborate why 6 are sent (which ones and for what purpose)?

To get all the necessary info with the inrupt sdk you need to call `getPublicAccess`, `getAgentAccessAll` and a function to get all group access (only applicable to the new `InruptPermissionManager` currently being implemented on the `refactor/controller-strategy-pattern` branch (#18)).
Each function sends a HEAD & GET request, the specific reason why is not stated in their docs.
If I'm allowed to do a guess, then it's probably to first check the existence of the ACL file followed to actually retrieve the ACL file's content
